### ISSUE TITLE
[US1] Create Button

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#1]
## Value proposition

As a user
I want to find a link that forwards me to a form
in order to create a new workout plan

## Description
![image](https://github.com/doctype-Melvin/capstone/assets/71100019/ca6e4ec9-6cf1-4de9-96e8-e743eaadd203)

## Acceptance criteria

- [x] there is a link that says 'create plan'
- [x] clicking the link forwards users to a form
- [x] the form view has a button to save the data
- [x] the form view has a button to go back/cancel the operation
- [x] the user can enter a plan name and how many days the plan should go

## Tasks

- [x] create new branch feature/create-button
- [x] add a button to pages/index.js
- [x] create a form component 
- [x] this component has an input field for name and days
- [x] there are two buttons
- [x] one button saves the form data
- [x] the other button allows users to abort plan creation
- [x]  implement form submit to handle user data
- [x]  create form page
- [x]  create a link component (your start button should be a link element)

**Comment by mbosselmann** [comment]
Hi Melvin,
good job! 👍 You thought about some acceptance criteria and tasks. Great! I have some remarks: 

## In general:
- Something that would be amazing for the user experience is that the submitted data can be displayed afterwards (maybe below the form?). Otherwise the user insert his data and nothing else happens after clicking the save button.
- Your start page should not only say "create plan", but also let the user know that he can enter his data to make a workout plan (as a plan could also be a meal plan, reading plan, plant care plan, chores plan, etc.). Maybe you can give this hint by adding a heading?

## Acceptance Criteria
The following tasks of this user story are described as they are acceptance criteria and not developer tasks. As they are great acceptance criteria, you can move them to the acceptance criteria part of the user story:

- there are two buttons
- one button saves the form data
- the other button allows users to abort plan creation

and you could add:
- the user can enter his name and how many days the plan should go

## Tasks
Good additional tasks could be:
- implement form submit to handle user data
- create form page
- create a link component (your start button should be a link element)

You can also think about other components that you may need (for displaying user data for example?).

I hope this does help! We are almost done, Melvin! 💪 
Feel free to ask me if you have further questions. :)

**Comment by mbosselmann** [comment]
Happy hacking! :octocat:

**Comment by doctype-Melvin** [comment]
thanks
