### ISSUE TITLE
[US5] Delete Exercise

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#11]
## Value proposition

As a user
I want to find a delete button when expanding the exercise card
in order to delete a given exercise from my plan

## Description

Currently users can create and update exercises. They should also be able to remove any exercise from their template.
The edit view of each exercise has a dumb delete button that does nothing yet. 

## Acceptance criteria

- [x] The delete button removes the matching exercise
- [x] 1. from database
- [x] 2. from view

## Tasks

- [x] create branch feature/delete-exercise
- [x] implement logic to remove exercises from database
- [x] make sure the exercise is removed from the view

Size:
