### ISSUE TITLE
[US 6] Save Template

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#12]
## Value proposition

As a user
I want to save my plan 
in order to use it as a template

## Description

When users have finished creating all of their exercises, they can click a `save` button which leads them to a template overview page. 

## Acceptance criteria

- [x] There's a save button at the end of the `createPlan` page
- [x] Clicking the button redirects users to an overview page
- [x] Here they can see all of their created templates
- [x] The overview page also has a `New Template` button to add a new template
- [x] This button leads users to a form

## Tasks

- [x] branch feat/save-template
- [x] create link to template overview
- [x] list all of the user's plans

Size:
