### ISSUE TITLE
[US 7] Navigation

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#13]
## Value proposition

As a user
I want to find a navigation element
in order to switch between different pages of the app

## Description

There's a navigation bar at the bottom of the screen.

## Acceptance criteria

- [x] There's a navigation bar at the bottom of the screen.
- [x] Icons are used to indicate the navigational destination
- [x] Tapping icons renders the desired view

## Tasks

- [x] create branch feat/navigation
- [x] implement a navigation bar at the screen's bottom
- [x] find conclusive icons
- [x] link icons to matching pages

Size:
