### ISSUE TITLE
[US 8] Delete templates

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#16]
## Value proposition

As a user
I want to be able to remove templates 
in order to keep my app tidy

## Description

The Overview of all templates should include a delete action for each template.

## Acceptance criteria

- [x] Users can click an icon in order to delete the matching template
- [x] The view rerenders upon clicking that icon
- [x] There are now less templates than before

## Tasks

- [x] create branch delete-template-button
- [x] create components for the template listing view
- [x] the components show an icon that unambiguously describes the action it's associated with (removing that template)

Size:

**Comment by cmgoersch** [comment]
Everything works wonderfully. That rocks!
Will you be able to change the number of training days after you have created a plan?

I'm curious what happens next with your app! 

Best regards :)

**Comment by doctype-Melvin** [comment]
Thank you Calle!
I thought about implementing what you're suggesting but I didn't even touch the core feature of my app yet. So, I guess I'll focus on that first and than after Bootcamp I might implement some other features that I couldn't fit into the current time frame.
