### ISSUE TITLE
[US 9] Select current template

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#17]
## Value proposition

As a user
I want to choose my current workout template
in order to keep track of my workout sessions

## Description

Within the individual template component there should be a button to mark a template as current. 
This template will then allow users to log their sessions accordingly (implementation at a later point in time).

## Acceptance criteria

- [x] Users can mark a desired template as their current plan
- [x] After making this selection, users are lead to the dashboard view
- [x] Here they see a sort of preview of their next session

## Tasks

- [x] implement the state management to set current template
- [x] take care of the redirect and the preview component
- [x] handle some of the navbar rendering issues

Size:
