### ISSUE TITLE
[US 10] Refactor Components

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#20]
## Value proposition

As a developer
I want to find only `index.js` files inside my component folders
in order to have my codebase comply with naming conventions

As a user
I want to see some sort of loading indicator
in order to know that my changes or navigation are in process

## Description

The current format of `ComponentName/ComponentName.js` will be changed to `ComponentName/index.js`
The isLoading state should be communicated clearly.

## Acceptance criteria

- [x] All component folders align with naming conventions
- [x] The 'Loading...' indicator is replaced with a dedicated component

## Tasks

- [x] Rename all of the js files inside component folders
- [x] Create a component for the isLoading useSWR state

Size:
