### ISSUE TITLE
[US11] Log workout sets

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#23]
## Value proposition

As a weightlifting trainee and user
I want to enter my repetition numbers at a given weight
in order to track my progress

## Description

Since users can now set their current template and are redirected to the next session dashboard, they should also be able to enter their reps for a given set. When users save their changes they can see a new entry in the session view. 

## Acceptance criteria

- [x] There is a dashboard icon in the navigation that links to the template's current workout session
- [x] Users may also click the respective link on the home screen to go to current template
- [x] Clicking on a day opens the logging view
- [x] Next to the exercise details is a button to add a new set
- [x] Clicking the button opens a form with two inputs and a save button
- [x] After entering numbers and hitting save, a new component is rendered
- [x] This new component shows the set details
- [x] Users may now click a button to edit the set details
- [x] User may now click a button to delete the set 

## Tasks

- [x] new branch
- [x] write frontend components
- [x] write frontend logic for handling workout set CRUD operations 
- [x] write backend for handling workout set CRUD operations 
- [x] give the whole app some basic styling

Size:

**Comment by antoniatandler** [comment]
works very well! congratulations 🥳
