### ISSUE TITLE
[US 12] Styling

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#25]
## Value proposition

As a user
I want to find coherent styling 
in order to find the app aesthetically pleasing

## Description

Some elements/components are in severe need of styling. 

## Acceptance criteria

- [ ] The app has a somewhat appealing appearance
- [x] PR1.1: When removing a workout set, users now need to confirm the deletion by tapping ✔️ 
- [ ] PR1.2: When removing a workout template, users now need to confirm the deletion by tapping ✔️ 

## Tasks

- [ ] Make the app look a bit prettier

Size:

**Comment by antoniatandler** [comment]
LGTM :)
