### ISSUE TITLE
[US2] Plan View

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#3]
## Value proposition

As a user
I want to be forwarded to my newly created workout plan
in order to add exercises to my routine

## Description

![image](https://github.com/doctype-Melvin/capstone/assets/71100019/f3e23c05-ce49-4492-8f65-432fe0acefbd)

## Acceptance criteria

- [x] hook up app to database
- [x] create the model for Plan app data
- [x] users are forwarded to the plan's page when saving the form with a name and days
- [x] they can see the plan's name and the workout frequency (number of days)
- [x] each workout day has its own component
- [x] each workout day component has a button to add an exercise

## Tasks

- [x] create a feature/plan-detail branch
- [x] render the plan's name 
- [x] create a WorkoutDay component
- [x] the WorkoutDay should show a string e.g.  'Day 1'
- [x] the WorkoutDay must have a button that says 'add exercise'

**Comment by t0bbl** [comment]
lgtm
just one small thing:
[ ] users are forwarded to the plan's page _when saving the form with a name and days_
or something like this would be a little more explanatory

**Comment by doctype-Melvin** [comment]
thanks
