### ISSUE TITLE
[US3] 'Add Exercise' form

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#4]
## Value proposition

As a user
I want to be able to save my exercises for any given workout day
in order to plan my week and see what to do on each day

## Description

![image](https://github.com/doctype-Melvin/capstone/assets/71100019/02b85f80-c6ee-471b-8eb5-96ab22dcbe5c)

## Acceptance criteria

- [x] users can click a button to add exercises
- [x] when clicking that button a new form appears in place
- [x] the form has an input field for each: exercise, sets, reps and weight
- [x] there is an add button 
- [x] there is also a cancel button to drop out of the process
- [x] for now, both buttons only toggle between form and workout day view

## Tasks

- [x] create feature branch
- [x] write a form component for the add exercise feature
- [x] implement the logic for in-place-toggling between form and workout day view

**Comment by t0bbl** [comment]
lgtm, just something minor:

> As a user
I want to be able to save my exercises for any given workout day
in order to use this app properly

something like 
> in order to plan my week and see what to do on each day

would be a little bit more explanatory

**Comment by doctype-Melvin** [comment]
Thank you for your suggestion. 
I just saw it now.
