### ISSUE TITLE
[US4] Adding and editing exercises

### ISSUE THREAD

**Issue by doctype-Melvin** [doctype-Melvin/capstone#8]
## Value proposition

As a user
I want to see and edit my added exercises
in order to keep my workout plan organized 

## Description

![image](https://github.com/doctype-Melvin/capstone/assets/71100019/1a826ba1-4685-48b2-92e7-c6b7753bf11d)

## Acceptance criteria

- [x] Clicking the 'cancel' button allows users to close the form
- [x] User's are required to enter data to successfully add an exercise
- [x] Clicking the 'add' button closes the form
- [x] App now renders the exercise in the matching workout day component
- [x] The exercise component shows the exercise name as a title
- [x] The exercise component has a collapsible child
- [x] Per default this child is collapsed
- [x] The collapsed child displays the exercise sets, reps and weight
- [x] The collapsed child should have an indicator icon that suggests expandability
- [x] The expanded child shows the exercise details and two buttons
- [x] One button should enable users to edit their exercise name and details (edit button)
- [x] Clicking the edit button opens the exercise form with the current exercise values
- [x] The already available exercise form should change the text content of the 'add' button to 'save'
- [x] The 'cancel' button will not be displayed in this render of the form
- [x] The 'save' button does two things:
- [x] 1. Closes the form 
- [x] 2. Updates the exercise component with updated values (if any changed)

## Tasks

- [x] Create new branch feat/process-exercise-data
- [x] Implement the logic to save form data
- [x] Write the exercise component
- [x] Implement the collapsed/expanded view of the exercise details
- [x] Apply exercise data update functionality
- [x] Write the conditional rendering logic for exercise form

Size:

**Comment by mzschunke** [comment]
Hey Melvin, very nice (and large) user story! 
Just one thing isn't quiet clear to me regarding the 4th criteria: Is _"view now"_ supposed to be a button/link in the overview page? I was wondering since I couldn't find it in the wireframes.

**Comment by doctype-Melvin** [comment]
Thanks for reviewing my user story.
You're referring to

> View now renders the exercise in the matching workout day component

I'd change it to 

> App now renders the exercise in the matching workout day component

What do you think? Let me know if this clears things up for you.

> very nice (and large) user story!

Gotta have something to do for the weekend.

**Comment by mzschunke** [comment]
That surely makes it more clear to me, since 'App' won't be mistaken for a button.

> Gotta have something to do for the weekend.

Good on you!  Happy hacking on the weekend :)
